### ISSUE TITLE
Segfault when using Breeze theme

### ISSUE THREAD

**Issue by PureTryOut** [sddm/sddm#1173]
Although the default theme works fine, it for some reason segfaults when using the Breeze theme.

```
qemu-amd64:~$ DISPLAY=:0 sddm-greeter --test-mode --theme /usr/share/sddm/themes/breeze
[11:00:24.034] (II) GREETER: High-DPI autoscaling not Enabled
[11:00:24.051] (WW) GREETER: QStandardPaths: XDG_RUNTIME_DIR not set, defaulting to '/tmp/runtime-bart'
[11:00:24.052] (II) GREETER: Reading from "/usr/share/xsessions/plasma.desktop"
[11:00:24.053] (II) GREETER: Reading from "/usr/share/wayland-sessions/plasmawayland.desktop"
[11:00:24.054] (II) GREETER: Loading theme configuration from "/usr/share/sddm/themes/breeze/theme.conf"
[11:00:24.062] (EE) GREETER: Socket error:  "QLocalSocket::connectToServer: Invalid name"
[11:00:24.203] (II) GREETER: Loading file:///usr/share/sddm/themes/breeze/Main.qml...
[11:00:24.260] (WW) GREETER: QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffea8d70c70), parent's thread is QThread(0x7f8646351900), current thread is QThread(0x55e6ba9fe840)
[11:00:24.261] (WW) GREETER: QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffea8d70c70), parent's thread is QThread(0x7f8646351900), current thread is QThread(0x55e6ba9fe840)
[11:00:24.262] (WW) GREETER: QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffea8d70c70), parent's thread is QThread(0x7f8646351900), current thread is QThread(0x55e6ba9fe840)
[11:00:24.263] (WW) GREETER: QObject: Cannot create children for a parent that is in a different thread.
(Parent is QGuiApplication(0x7ffea8d70c70), parent's thread is QThread(0x7f8646351900), current thread is QThread(0x55e6ba9fe840)
[11:00:24.263] (WW) GREETER: QObject::installEventFilter(): Cannot filter events for objects in a different thread.
[11:00:24.265] (II) GREETER: Loaded plugin "/usr/lib/qt5/plugins/kf5/org.kde.kwindowsystem.platforms/KF5WindowSystemX11Plugin.so" for platform "xcb"
[11:00:24.347] (WW) GREETER: Cannot watch QRC-like path ":/icons/hicolor/index.theme"
Segmentation fault
```

This is on Alpine Linux, using Qt 5.12.3, Musl 1.1.22, Breeze 5.15.5 and SDDM 0.18.1. I blame some missing package but I can't figure out what.

`gdb` backtrace:
```
#0  0x00007ffff6c8c035 in ?? () from /usr/lib/libQt5Core.so.5
#1  0x00007ffff6c8d686 in ?? () from /usr/lib/libQt5Core.so.5
#2  0x00007ffff6c8dba6 in ?? () from /usr/lib/libQt5Core.so.5
#3  0x00007ffff6c32127 in QDateTime::setMSecsSinceEpoch(long long) () from /usr/lib/libQt5Core.so.5
#4  0x00007ffff6c33f48 in QDateTime::fromMSecsSinceEpoch(long long, QTimeZone const&) () from /usr/lib/libQt5Core.so.5
#5  0x00007ffff6c33fbc in QDateTime::toTimeZone(QTimeZone const&) const () from /usr/lib/libQt5Core.so.5
#6  0x00007fffec4b23b3 in ?? () from /usr/lib/qt5/plugins/plasma/dataengine/plasma_engine_time.so
#7  0x00007fffec4b29f8 in ?? () from /usr/lib/qt5/plugins/plasma/dataengine/plasma_engine_time.so
#8  0x00007fffec4b2ac6 in ?? () from /usr/lib/qt5/plugins/plasma/dataengine/plasma_engine_time.so
#9  0x00007fffec4b0fad in ?? () from /usr/lib/qt5/plugins/plasma/dataengine/plasma_engine_time.so
#10 0x00007fffedd305c8 in ?? () from /usr/lib/libKF5Plasma.so.5
#11 0x00007fffedd30b51 in Plasma::DataEngine::connectSource(QString const&, QObject*, unsigned int, Plasma::Types::IntervalAlignment) const () from /usr/lib/libKF5Plasma.so.5
#12 0x00007fffede35df8 in ?? () from /usr/lib/qt5/qml/org/kde/plasma/core/libcorebindingsplugin.so
#13 0x00007fffede27247 in ?? () from /usr/lib/qt5/qml/org/kde/plasma/core/libcorebindingsplugin.so
#14 0x00007ffff7971b35 in ?? () from /usr/lib/libQt5Qml.so.5
#15 0x00007ffff7970bc1 in QQmlPropertyPrivate::write(QObject*, QQmlPropertyData const&, QVariant const&, QQmlContextData*, QFlags<QQmlPropertyData::WriteFlag>) () from /usr/lib/libQt5Qml.so.5
#16 0x00007ffff797174a in QQmlPropertyPrivate::writeValueProperty(QObject*, QQmlPropertyData const&, QQmlPropertyData const&, QVariant const&, QQmlContextData*, QFlags<QQmlPropertyData::WriteFlag>) ()
   from /usr/lib/libQt5Qml.so.5
#17 0x00007ffff79b6de6 in QQmlBinding::slowWrite(QQmlPropertyData const&, QQmlPropertyData const&, QV4::Value const&, bool, QFlags<QQmlPropertyData::WriteFlag>) () from /usr/lib/libQt5Qml.so.5
#18 0x00007ffff79b781d in ?? () from /usr/lib/libQt5Qml.so.5
#19 0x00007ffff79b7f01 in ?? () from /usr/lib/libQt5Qml.so.5
#20 0x00007ffff79b663c in QQmlBinding::update(QFlags<QQmlPropertyData::WriteFlag>) () from /usr/lib/libQt5Qml.so.5
#21 0x00007ffff79c0054 in QQmlObjectCreator::finalize(QQmlInstantiationInterrupt&) () from /usr/lib/libQt5Qml.so.5
#22 0x00007ffff7972546 in QQmlComponentPrivate::complete(QQmlEnginePrivate*, QQmlComponentPrivate::ConstructionState*) () from /usr/lib/libQt5Qml.so.5
#23 0x00007ffff797262d in QQmlComponentPrivate::completeCreate() () from /usr/lib/libQt5Qml.so.5
#24 0x00007ffff797379d in QQmlComponent::create(QQmlContext*) () from /usr/lib/libQt5Qml.so.5
#25 0x00007ffff7dbc8da in QQuickView::continueExecute() () from /usr/lib/libQt5Quick.so.5
#26 0x00007ffff7dbcbf4 in QQuickViewPrivate::execute() () from /usr/lib/libQt5Quick.so.5
#27 0x00005555555a22d5 in SDDM::GreeterApp::addViewForScreen(QScreen*) ()
#28 0x00005555555a2965 in SDDM::GreeterApp::startup() ()
#29 0x00005555555a10f3 in SDDM::GreeterApp::customEvent(QEvent*) ()
#30 0x00007ffff6ddcc8b in QObject::event(QEvent*) () from /usr/lib/libQt5Core.so.5
#31 0x00007ffff6db2739 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () from /usr/lib/libQt5Core.so.5
#32 0x00007ffff6db57b7 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) () from /usr/lib/libQt5Core.so.5
#33 0x00007ffff6e06e73 in ?? () from /usr/lib/libQt5Core.so.5
#34 0x00007ffff5dde382 in g_main_context_dispatch () from /usr/lib/libglib-2.0.so.0
#35 0x00007ffff5dde5fb in ?? () from /usr/lib/libglib-2.0.so.0
#36 0x00007ffff5dde6a9 in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#37 0x00007ffff6e06433 in QEventDispatcherGlib::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#38 0x00007ffff6db13db in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) () from /usr/lib/libQt5Core.so.5
#39 0x00007ffff6db9472 in QCoreApplication::exec() () from /usr/lib/libQt5Core.so.5
#40 0x00005555555a3757 in main ()
```

**Comment by davidedmundson** [comment]
Fixed properly in unreleased new Qt
Worked round in latest plasma.
