### ISSUE TITLE
Crash when using touch screen with wayland

### ISSUE THREAD

**Issue by plata** [sddm/sddm#1625]
If I use keyboard and mouse, everything works somewhat normal (except that the keyboard layout is wrong). As soon as I touch the touch screen, sddm crashes (white blinking cursor on black background).

```
[General]
DisplayServer=wayland
GreeterEnvironment=QT_WAYLAND_SHELL_INTEGRATION=layer-shell

[Wayland]
SessionDir=/usr/share/wayland-sessions
SessionLogFile=.local/share/sddm/wayland-session.log
CompositorCommand=kwin_wayland --no-lockscreen --inputmethod maliit-keyboard
```

**Comment by aleixpol** [comment]
We will need a backtrace, you can get it by using `coredumpctl` on a terminal.

**Comment by plata** [comment]
It seems that actually `kwin_wayland` crashes:
```
Core was generated by `/usr/bin/kwin_wayland --no-lockscreen --inputmethod maliit-keyboard'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x00007f94d1600554 in KWin::Output::modeSize() const () from /usr/lib/libkwin.so.5
[Current thread is 1 (Thread 0x7f94ca951880 (LWP 483))]
(gdb) bt
#0  0x00007f94d1600554 in KWin::Output::modeSize() const () at /usr/lib/libkwin.so.5
#1  0x00007f94d17b5e85 in KWin::LibInput::Connection::processEvents() () at /usr/lib/libkwin.so.5
#2  0x00007f94cff74be0 in QObject::event(QEvent*) () at /usr/lib/libQt5Core.so.5
#3  0x00007f94cf4c0b1c in QApplicationPrivate::notify_helper(QObject*, QEvent*) ()
    at /usr/lib/libQt5Widgets.so.5
#4  0x00007f94cff50f98 in QCoreApplication::notifyInternal2(QObject*, QEvent*) () at /usr/lib/libQt5Core.so.5
#5  0x00007f94cff51aa3 in QCoreApplicationPrivate::sendPostedEvents(QObject*, int, QThreadData*) ()
    at /usr/lib/libQt5Core.so.5
#6  0x00007f94cff9b557 in QEventDispatcherUNIX::processEvents(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#7  0x000055eba9da2b52 in  ()
#8  0x00007f94cff4973c in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
    at /usr/lib/libQt5Core.so.5
#9  0x00007f94cff54269 in QCoreApplication::exec() () at /usr/lib/libQt5Core.so.5
#10 0x000055eba9cc3611 in  ()
#11 0x00007f94ced91290 in  () at /usr/lib/libc.so.6
#12 0x00007f94ced9134a in __libc_start_main () at /usr/lib/libc.so.6
#13 0x000055eba9cc4c95 in  ()
```

**Comment by plata** [comment]
Doesn't happen anymore.
