### ISSUE TITLE
Segfault at first start after boot

### ISSUE THREAD

**Issue by PlasmaHH** [sddm/sddm#1776]
When first booting my opensuse tumbleweed the sddm-greeter process ( version 0.20.0-2.1 ) segfaults. Killing the Xorg server after that it will start fine again.

![image](https://github.com/sddm/sddm/assets/1965659/a8284bb3-bec3-4150-81f7-9bc47d6f8b08)

It seems that in XcbKeyboardBackend.cpp 121 the reply pointer is null, being returned previously from a call to xcb_xkb_get_names_reply ... No idea why then the error variable is not set, but I have no knowledge of teh xcb api. 

Maybe it is sufficient to just consider that as an error case the same as wenn the error pointer is set?

**Comment by Vogtinator** [comment]
Maybe, but I wonder why there is no reply. Any unusual keyboard configuration?

**Comment by PlasmaHH** [comment]
Not sure what would be considered unusual. It is a laptop with a wireless usb keyboard attached... sometimes directly, sometimes through a TB4 dock) any commands I could try running? Not sure if they would  show the same information as sddm, or the issued fixed itself until they are run... (. What is weird is that the second time ( after I kill the X server ) it starts just fine

**Comment by minamfg** [comment]
i have similar problem on a completely normal hardware with usb keyboarrd 
```bash
CPU: 8-core (4-mt/4-st) 12th Gen Intel Core i5-12450HX (-MST AMCP-)
speed/min/max: 800/800/4400:3100 MHz Kernel: 6.12.0-160000.36-default x86_64
Up: 1h 25m Mem: 4.8/11.39 GiB (42.1%) Storage: 476.94 GiB (5.3% used)
Procs: 360 Shell: Bash 5.2.37 inxi: 3.3.36
mina@Mina-LPC:~> sudo inxi  -za
[sudo] password for mina: 
CPU: 8-core (4-mt/4-st) 12th Gen Intel Core i5-12450HX (-MST AMCP-)
speed/min/max: 800/800/4400:3100 MHz Kernel: 6.12.0-160000.36-default x86_64 Up: 1h 25m
Mem: 4.81/11.39 GiB (42.2%) Storage: 476.94 GiB (5.3% used) Procs: 362 Shell: Sudo 1.9.17p1
inxi: 3.3.36
mina@Mina-LPC:~> sudo inxi  -za -v8
System:
  Kernel: 6.12.0-160000.36-default arch: x86_64 bits: 64 compiler: gcc v: 13.4.0 clocksource: tsc
    avail: acpi_pm parameters: BOOT_IMAGE=/vmlinuz-6.12.0-160000.36-default
    root=UUID=d2afd20f-5248-444f-babe-edd13ef1eba5 mediacheck=1 plymouth.enable=0
    resume=/dev/disk/by-uuid/dc852ca3-c28a-4991-b357-11dd036e26b2 mitigations=auto quiet
    security=selinux selinux=1 rd.driver.blacklist=nouveau
  Console: pty pts/1 DM: SDDM Distro: openSUSE Leap 16.0
Machine:
  Type: Laptop System: LENOVO product: 83GS v: LOQ 15IAX9 serial: <filter> Chassis: type: 10
    v: LOQ 15IAX9 serial: <filter>
  Mobo: LENOVO model: LNVNB161216 v: SDK0T76509 WIN serial: <filter>
    part-nu: LENOVO_MT_83GS_BU_idea_FM_LOQ 15IAX9 uuid: 4152cd77-5884-11f0-a4f9-40c2bad035e5
    UEFI: LENOVO v: NECN47WW date: 09/12/2025
Battery:
  ID-1: BAT1 charge: 47.7 Wh (78.6%) condition: 60.7/60.0 Wh (101.2%) volts: 15.9 min: 15.4
    model: Sunwoda L23D4PK4 type: Li-poly serial: <filter> status: not charging cycles: 8
Memory:
  System RAM: total: 12 GiB available: 11.39 GiB used: 4.69 GiB (41.1%) igpu: 60 MiB
  Array-1: capacity: 64 GiB slots: 2 modules: 1 EC: None max-module-size: 32 GiB note: est.
  Device-1: Controller0-ChannelA-DIMM0 type: DDR5 detail: synchronous size: 12 GiB
    speed: 4800 MT/s volts: curr: 1.1 width (bits): data: 64 total: 64
    manufacturer: Ramaxel Technology part-no: RMSB3400KB06IVF-4800 serial: <filter>
  Device-2: Controller1-ChannelA-DIMM0 type: no module installed
PCI Slots:
  Slot: 1 type: PCIe status: in use info: J6C1 length: other bus-ID: 00:1c.0 children: 1: 07:00.0
    class-ID: 0200 type: network
  Slot: 2 type: PCIe status: available info: J6D2 length: other bus-ID: 00:1c.1
  Slot: 3 type: PCIe status: available info: J7C1 length: other bus-ID: 00:1c.2
  Slot: 4 type: PCIe status: available info: J7D1 length: other bus-ID: 00:1c.3
  Slot: 5 type: PCIe status: available info: J8C1 length: other bus-ID: 00:1c.4
CPU:
  Info: model: 12th Gen Intel Core i5-12450HX socket: LGA1700 (U3E1) note: check bits: 64
    type: MST AMCP arch: Alder Lake gen: core 12 level: v3 note: check built: 2021+
    process: Intel 7 (10nm ESF) family: 6 model-id: 0x97 (151) stepping: 2 microcode: 0x3E
  Topology: cpus: 1x dies: 1 clusters: 5 cores: 8 threads: 12 mt: 4 tpc: 2 st: 4 smt: enabled
    cache: L1: 704 KiB desc: d-4x32 KiB, 4x48 KiB; i-4x32 KiB, 4x64 KiB L2: 7 MiB
    desc: 4x1.2 MiB, 1x2 MiB L3: 12 MiB desc: 1x12 MiB
  Speed (MHz): avg: 800 min/max: 800/4400:3100 base/boost: 4158/4500 scaling:
    driver: intel_pstate governor: powersave volts: 1.1 V ext-clock: 100 MHz cores: 1: 800 2: 800
    3: 800 4: 800 5: 800 6: 800 7: 800 8: 800 9: 800 10: 800 11: 800 12: 800 bogomips: 64512
  Flags: 3dnowprefetch abm acpi adx aes aperfmperf apic arat arch_capabilities arch_lbr
    arch_perfmon art avx avx2 avx_vnni bmi1 bmi2 bts clflush clflushopt clwb cmov constant_tsc
    cpuid cpuid_fault cx16 cx8 de ds_cpl dtes64 dtherm dts epb ept ept_ad erms est f16c
    flexpriority flush_l1d fma fpu fsgsbase fsrm fxsr gfni hfi ht hwp hwp_act_window hwp_epp
    hwp_notify hwp_pkg_req ibpb ibrs ibrs_enhanced ibt ida intel_pt invpcid lahf_lm lm mca mce
    md_clear mmx monitor movbe movdir64b movdiri msr mtrr nonstop_tsc nopl nx ospke pae pat pbe
    pclmulqdq pdcm pdpe1gb pebs pge pku pln pni popcnt pse pse36 pts rdpid rdrand rdseed rdtscp
    rep_good sdbg sep serialize sha_ni smap smep split_lock_detect ss ssbd sse sse2 sse4_1 sse4_2
    ssse3 stibp syscall tm tm2 tpr_shadow tsc tsc_adjust tsc_deadline_timer tsc_known_freq umip
    user_shstk vaes vme vmx vnmi vpclmulqdq vpid waitpkg x2apic xgetbv1 xsave xsavec xsaveopt
    xsaves xtopology xtpr
  Vulnerabilities:
  Type: gather_data_sampling status: Not affected
  Type: indirect_target_selection status: Not affected
  Type: itlb_multihit status: Not affected
  Type: l1tf status: Not affected
  Type: mds status: Not affected
  Type: meltdown status: Not affected
  Type: mmio_stale_data status: Not affected
  Type: reg_file_data_sampling mitigation: Clear Register File
  Type: retbleed status: Not affected
  Type: spec_rstack_overflow status: Not affected
  Type: spec_store_bypass mitigation: Speculative Store Bypass disabled via prctl
  Type: spectre_v1 mitigation: usercopy/swapgs barriers and __user pointer sanitization
  Type: spectre_v2 mitigation: Enhanced / Automatic IBRS; IBPB: conditional; PBRSB-eIBRS: SW
    sequence; BHI: BHI_DIS_S
  Type: srbds status: Not affected
  Type: tsa status: Not affected
  Type: tsx_async_abort status: Not affected
  Type: vmscape mitigation: IBPB before exit to userspace
Graphics:
  Device-1: Intel Alder Lake-S [UHD Graphics] vendor: Lenovo driver: i915 v: kernel alternate: xe
    arch: Gen-12.1 process: Intel 10nm built: 2020-21 ports: active: none off: eDP-1 empty: DP-1,
    DP-2, HDMI-A-1, HDMI-A-2, HDMI-A-3, HDMI-A-4 bus-ID: 00:02.0 chip-ID: 8086:468b class-ID: 0300
  Device-2: NVIDIA GA107 [GeForce RTX 2050] vendor: Lenovo driver: nvidia v: 595.84
    alternate: nouveau,nvidia_drm non-free: 550.xx+ status: current (as of 2024-09; EOL~2026-12-xx)
    arch: Turing code: TUxxx process: TSMC 12nm FF built: 2018-2022 pcie: gen: 1 speed: 2.5 GT/s
    lanes: 8 link-max: gen: 4 speed: 16 GT/s lanes: 16 ports: active: HDMI-A-5 empty: DP-3,eDP-2
    bus-ID: 01:00.0 chip-ID: 10de:25ed class-ID: 0300
  Device-3: Chicony Integrated Camera driver: uvcvideo type: USB rev: 2.0 speed: 480 Mb/s
    lanes: 1 mode: 2.0 bus-ID: 1-6:2 chip-ID: 04f2:b7ec class-ID: fe01 serial: <filter>
  Display: unspecified server: X.org v: 1.21.1.15 with: Xwayland v: 24.1.6
    compositor: kwin_wayland driver: X: loaded: modesetting,nvidia unloaded: vesa
    alternate: fbdev,intel,nouveau,nv dri: iris gpu: i915,nv_platform,nvidia,nvidia-nvswitch
    tty: 151x36
  Monitor-1: HDMI-A-5 model: Samsung SMB1930N serial: <filter> built: 2011 res: 1366x768 dpi: 85
    gamma: 1.2 chroma: red: x: 0.651 y: 0.337 green: x: 0.290 y: 0.604 blue: x: 0.141 y: 0.071
    white: x: 0.314 y: 0.329 size: 410x230mm (16.14x9.06") diag: 470mm (18.5") ratio: 16:9
    modes: 1366x768, 1920x1080, 1280x720, 1024x768, 800x600, 720x480, 640x480
  Monitor-2: eDP-1 model-id: CSW 0x150f serial: <filter> built: 2023 res: 1920x1080 dpi: 142
    gamma: 1.2 chroma: red: x: 0.639 y: 0.333 green: x: 0.298 y: 0.612 blue: x: 0.149 y: 0.051
    white: x: 0.314 y: 0.329 size: 344x193mm (13.54x7.6") diag: 394mm (15.5") ratio: 16:9
    modes: 1920x1080
  EDID-Warnings: 1: parse_edid: unknown tag 112
  API: EGL v: 1.5 hw: drv: intel iris drv: nvidia platforms: device: 0 drv: nvidia device: 1
    drv: iris gbm: drv: iris surfaceless: drv: nvidia inactive: wayland,x11
  API: OpenGL v: 4.6.0 compat-v: 4.6 vendor: mesa v: 24.3.3 note: console (EGL sourced)
    renderer: Mesa Intel UHD Graphics (ADL-S GT0.5), NVIDIA GeForce RTX 2050/PCIe/SSE2
  API: Vulkan v: 1.4.309 layers: 3 device: 0 type: integrated-gpu name: Intel UHD Graphics
    (ADL-S GT0.5) driver: N/A device-ID: 8086:468b surfaces: N/A device: 1 type: discrete-gpu
    name: NVIDIA GeForce RTX 2050 driver: N/A device-ID: 10de:25ed surfaces: N/A
Audio:
  Device-1: Intel Alder Lake-S HD Audio vendor: Lenovo driver: snd_hda_intel v: kernel
    alternate: snd_soc_avs,snd_sof_pci_intel_tgl bus-ID: 00:1f.3 chip-ID: 8086:7ad0 class-ID: 0401
  Device-2: NVIDIA GA107 High Definition Audio vendor: Lenovo driver: snd_hda_intel v: kernel
    pcie: gen: 4 speed: 16 GT/s lanes: 8 link-max: lanes: 16 bus-ID: 01:00.1 chip-ID: 10de:2291
    class-ID: 0403
  API: ALSA v: k6.12.0-160000.36-default status: kernel-api tools: N/A
  Server-1: PipeWire v: 1.4.6 status: n/a (root, process) with: 1: pipewire-pulse status: active
    2: wireplumber status: active 3: pipewire-alsa type: plugin 4: pw-jack type: plugin
    tools: pactl,pw-cat,pw-cli,wpctl
```

and here is the Backtrace
```
Reading symbols from /usr/bin/sddm-greeter-qt6...
Reading symbols from /usr/lib/debug/usr/bin/sddm-greeter-qt6.debug...
[New LWP 2005]
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib64/libthread_db.so.1".
Core was generated by `/usr/bin/sddm-greeter-qt6 --socket /tmp/sddm-:0-WHTNsq --theme /usr/share/sddm/themes/breeze-openSUSE'.
Program terminated with signal SIGSEGV, Segmentation fault.
#0  0x0000563b2bdda5fa in SDDM::XcbKeyboardBackend::initLedMap (this=0x563b332c7c60)
    at /usr/src/debug/sddm-0.21.0/src/greeter/XcbKeyboardBackend.cpp:121
121           xcb_xkb_get_names_value_list_unpack(buffer, reply->nTypes, reply->indicators,
(gdb) bt
#0  0x0000563b2bdda5fa in SDDM::XcbKeyboardBackend::initLedMap (this=0x563b332c7c60)
    at /usr/src/debug/sddm-0.21.0/src/greeter/XcbKeyboardBackend.cpp:121
#1  SDDM::XcbKeyboardBackend::init (this=0x563b332c7c60) at /usr/src/debug/sddm-0.21.0/src/greeter/XcbKeyboardBackend.cpp:41
#2  0x0000563b2bddacbf in SDDM::KeyboardModel::KeyboardModel (this=<optimized out>, this=<optimized out>)
    at /usr/src/debug/sddm-0.21.0/src/greeter/KeyboardModel.cpp:36
#3  0x0000563b2bde2527 in SDDM::GreeterApp::GreeterApp(QObject*) [clone .constprop.0] (this=0x563b332c7e30, parent=0x0)
    at /usr/src/debug/sddm-0.21.0/src/greeter/GreeterApp.cpp:67
#4  0x0000563b2bdc1a72 in main (argc=<optimized out>, argv=<optimized out>) at /usr/src/debug/sddm-0.21.0/src/greeter/GreeterApp.cpp:388
```
