### ISSUE TITLE
Crash when switching tty

### ISSUE THREAD

**Issue by dolohow** [sddm/sddm#640]
When switching tty's with Ctrl+Alt+F[1-7] using amdgpu module with disabled fbdev sddm crashes every time.

```
Thread 2 (Thread 0x7ff75e29b700 (LWP 464)):
#0  0x00007ff76344468d in poll () from /usr/lib/libc.so.6
#1  0x00007ff760427fd6 in ?? () from /usr/lib/libglib-2.0.so.0
#2  0x00007ff7604280ec in g_main_context_iteration () from /usr/lib/libglib-2.0.so.0
#3  0x00007ff763f7b6cf in ?? () from /usr/lib/libQt5Core.so.5
#4  0x00007ff75e29add0 in ?? ()
#5  0x0000000000000024 in ?? ()
#6  0x00007ff75e29add0 in ?? ()
#7  0x00007ff758003204 in ?? ()
#8  0x0000000000be2540 in ?? ()
#9  0x00007ff758003190 in ?? ()
#10 0x00007ffe1b628940 in ?? ()
#11 0x00007ff763f2346a in QEventLoop::exec(QFlags<QEventLoop::ProcessEventsFlag>) ()
   from /usr/lib/libQt5Core.so.5
#12 0x00007ff763d4a2f3 in QThread::exec() () from /usr/lib/libQt5Core.so.5
#13 0x00007ff764ce7a65 in ?? () from /usr/lib/libQt5DBus.so.5
#14 0x00007ff763d4f1d8 in ?? () from /usr/lib/libQt5Core.so.5
#15 0x00007ff763150474 in start_thread () from /usr/lib/libpthread.so.0
#16 0x00007ff76344d69d in clone () from /usr/lib/libc.so.6

Thread 1 (Thread 0x7ff7650b57c0 (LWP 428)):
#0  0x00007ff763f58ad3 in QObject::connect(QObject const*, char const*, QObject const*, char const*, Qt::ConnectionType) () from /usr/lib/libQt5Core.so.5
#1  0x000000000042fed5 in SDDM::Auth::Private::setSocket(QLocalSocket*) ()
#2  0x0000000000431c24 in SDDM::Auth::SocketServer::handleNewConnection() ()
#3  0x00007ff763f52679 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#4  0x00007ff76445945f in ?? () from /usr/lib/libQt5Network.so.5
#5  0x00007ff763f52679 in QMetaObject::activate(QObject*, int, int, void**) () from /usr/lib/libQt5Core.so.5
#6  0x00007ff763fcf51e in ?? () from /usr/lib/libQt5Core.so.5
#7  0x00000000005dd0cd in ?? ()
#8  0x000000101be88100 in ?? ()
#9  0x0000000000000000 in ?? ()
```

**Comment by tigerjack** [comment]
Same here with amdgpu and fbdev completely removed from the system.
